Hw 28.1
Rudiachenko/jv-internet-shop pull request #6
Opened 2020-09-14 17:46 UTC by Rudiachenko

2020-09-14 18:02 UTC, frostpv commented on src/main/java/com/internet/shop/dao/impl/UserDaoImpl.java
> +                .filter(u -> u.getLogin().equals(login))
я бы использовал полное название переменной.

2020-09-14 18:02 UTC, frostpv commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +                new AuthenticationException("You entered incorrect username"));
Не нужно давать хакерам возможность проверять есть ли логин в системе или нет на этапе входа)))) Это конечно шутка, просто пользователю следует знать хотя бы свой логин, а наша система не знает кто его вводи поэтому и не может говорить корректный он или нет)))

2020-09-14 18:02 UTC, frostpv commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +                new AuthenticationException("You entered incorrect username"));
You entered incorrect login по логике

2020-09-15 08:25 UTC, KseniiaMakarova requested changes

2020-09-15 08:25 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/user/LoginController.java
> +            session.setAttribute("userId", user.getId());
let's make `userId` constant

2020-09-15 08:25 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +        if (!userFromDB.getPassword().equals(password)) {
let's check all conditions inside `if` so that we could throw our Exception only once

2020-09-15 08:25 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/web/filters/AuthenticationFilter.java
> +            resp.sendRedirect("/login");
```suggestion
            resp.sendRedirect(req.getContextPath() + "/login");
```

2020-09-15 10:24 UTC, KseniiaMakarova approved these changes

2020-09-15 10:28 UTC, merged