Added Product to MySQL
Rudiachenko/jv-internet-shop pull request #9
Opened 2020-09-19 22:37 UTC by Rudiachenko

2020-09-20 08:31 UTC, andromash requested changes
Good job!

2020-09-20 08:31 UTC, andromash commented on src/main/java/com/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            }
you can make a return already here

2020-09-20 08:31 UTC, andromash commented on src/main/java/com/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +
```suggestion
```

2020-09-20 08:31 UTC, andromash commented on src/main/java/com/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            }
you can make return right here

2020-09-20 08:31 UTC, andromash commented on src/main/java/com/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +    private Product createProduct(ResultSet resultSet) throws SQLException {
does this name describe fully what it does?

2020-09-20 08:31 UTC, andromash commented on src/main/resources/init_db.sql
> +  `name` VARCHAR(45) NOT NULL,
is this size enough?

2020-09-21 08:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/application/Main.java
> +        ProductDaoJdbcImpl productDaoJdbc = new ProductDaoJdbcImpl();
- let's use injector)
- we can remove dao annotation above ProductDaoImpl class

2020-09-21 08:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +    public Product create(Product item) {
```suggestion
    public Product create(Product product) {
```

2020-09-21 08:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +                    + "VALUES (?, ?);";
```suggestion
            String query = "INSERT INTO products (name, price) VALUES (?, ?);";
```

2020-09-21 08:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +                    + "WHERE product_id = ?;";
```suggestion
            String query = "SELECT * FROM products WHERE product_id = ?;";
```
should we get deleted a product?

2020-09-21 08:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            resultSet.next();
what does happen if resultSet.next() == null?

2020-09-21 08:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            String query = "SELECT * FROM products;";
how about the deleted products?

2020-09-21 08:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            String query = "UPDATE products "
- can we update deleted data?
- let's combine 3 lines into two or one

2020-09-21 08:34 UTC, Sofasmile commented on src/main/java/com/internet/shop/dao/jdbc/ProductDaoJdbcImpl.java
> +            return true;
should we always return true? let's check the result of statement.executeUpdate() and return the result of checking

2020-09-21 08:34 UTC, Sofasmile commented on src/main/resources/init_db.sql
> +  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE);
should product_name has UNIQUE INDEX and product_id too?

2020-09-21 12:13 UTC, Sofasmile approved these changes

2020-09-21 12:25 UTC, merged